name: TopVoteLeaderboard
api: [5.0.0]
version: 2.0.0
author: reyyoga & AlvinHere
main: reyyoga\Main

commands:
 settopvote:
     description: "set leaderboard location"
     permission: "settopvote.lb"
permissions:
  settopvote.lb:
    description: "topmineleaderboard command permission!"
    default: op
